from .CRCH import ComusRch
from .CGHB import ComusGhb
from .CDRN import ComusDrn
from .CHFB import ComusHfb
from .CWEL import ComusWel
from .CSHB import ComusShb
from .CEVT import ComusEvt
from .CRIV import ComusRiv
from .CRES import ComusRes
from .CSTR import ComusStr
from .CLAK import ComusLak
from .CIBS import ComusIbs
from .CSUB import ComusSub
from .CREG import ComusReg
