# Generated by Django 3.2.23 on 2024-05-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComusDisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comus_model',
            },
        ),
        migrations.CreateModel(
            name='ComusBcfPropModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'comus_bcf_property',
            },
        ),
        migrations.CreateModel(
            name='ComusCtrlParsModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('num_layer', models.IntegerField(default=1)),
                ('num_row', models.IntegerField(default=1)),
                ('num_col', models.IntegerField(default=1)),
                ('dim_unit', models.CharField(default='m', max_length=10)),
                ('time_unit', models.CharField(default='day', max_length=10)),
                ('x_coord', models.FloatField(default=0)),
                ('y_coord', models.FloatField(default=0)),
                ('sim_mtd', models.IntegerField(default=1)),
                ('sim_type', models.IntegerField(default=2)),
                ('acc_lambda', models.FloatField(default=-1)),
                ('intblkm', models.IntegerField(default=1)),
                ('solve', models.IntegerField(default=2)),
                ('max_iter', models.IntegerField(default=200)),
                ('damp', models.FloatField(default=1)),
                ('h_close', models.FloatField(default=0.0001)),
                ('r_close', models.FloatField(default=0.001)),
                ('relax', models.IntegerField(default=0)),
                ('theta', models.FloatField(default=0.7)),
                ('gamma', models.FloatField(default=3)),
                ('akappa', models.FloatField(default=0.001)),
                ('n_iter', models.IntegerField(default=5)),
                ('hno_flo', models.FloatField(default=-1e+30)),
                ('ch_flg', models.IntegerField(default=0)),
                ('wd_flg', models.IntegerField(default=0)),
                ('wet_fct', models.FloatField(default=0.1)),
                ('newt_iter', models.IntegerField(default=1)),
                ('hd_wet', models.IntegerField(default=1)),
                ('reg_sta', models.IntegerField(default=0)),
                ('mul_td', models.IntegerField(default=0)),
                ('num_td', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'comus_ctrl_pars',
            },
        ),
        migrations.CreateModel(
            name='ComusGridParsModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_grid_pars',
            },
        ),
        migrations.CreateModel(
            name='ComusLpfPropModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'comus_lpf_property',
            },
        ),
        migrations.CreateModel(
            name='ComusOutParsModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('gdw_bd', models.IntegerField(default=1)),
                ('lyr_bd', models.IntegerField(default=1)),
                ('cell_bd', models.IntegerField(default=1)),
                ('cell_hh', models.IntegerField(default=1)),
                ('cell_dd', models.IntegerField(default=1)),
                ('cell_flo', models.IntegerField(default=1)),
                ('lak_bd', models.IntegerField(default=1)),
                ('segm_bd', models.IntegerField(default=1)),
                ('rech_bd', models.IntegerField(default=1)),
                ('ibs', models.IntegerField(default=1)),
                ('sub', models.IntegerField(default=1)),
                ('ndb', models.IntegerField(default=1)),
                ('db', models.IntegerField(default=1)),
                ('reg_bd', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'comus_out_pars',
            },
        ),
        migrations.CreateModel(
            name='ComusPeriodModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('period', models.JSONField()),
            ],
            options={
                'db_table': 'comus_period',
            },
        ),
        migrations.CreateModel(
            name='ComusSpaceModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'comus_space',
            },
        ),
    ]
