# Generated by Django 3.2.23 on 2024-05-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComusDis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comusdismodel',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
