# Generated by Django 3.2.23 on 2024-05-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComusDis', '0002_alter_comusdismodel_user_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comusdismodel',
            unique_together={('user_name', 'project_name')},
        ),
    ]
