# Generated by Django 3.2.23 on 2024-05-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ComusDis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComusDRNModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('cond', models.JSONField(blank=True, null=True)),
                ('delev', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_drn',
            },
        ),
        migrations.CreateModel(
            name='ComusEVTModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('et_surf', models.JSONField(blank=True, null=True)),
                ('et_rate', models.JSONField(blank=True, null=True)),
                ('et_mxd', models.JSONField(blank=True, null=True)),
                ('et_exp', models.JSONField(blank=True, null=True)),
                ('evt', models.IntegerField(default=1)),
                ('num_seg', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'comus_evt',
            },
        ),
        migrations.CreateModel(
            name='ComusGHBModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('cond', models.JSONField(blank=True, null=True)),
                ('shead', models.JSONField(blank=True, null=True)),
                ('ehead', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_ghb',
            },
        ),
        migrations.CreateModel(
            name='ComusHFBModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('hfb_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_hfb',
            },
        ),
        migrations.CreateModel(
            name='ComusIBSModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('hc', models.JSONField(blank=True, null=True)),
                ('sfe', models.JSONField(blank=True, null=True)),
                ('sfv', models.JSONField(blank=True, null=True)),
                ('com', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_ibs',
            },
        ),
        migrations.CreateModel(
            name='ComusLAKCtrlModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_lak_ctrl',
            },
        ),
        migrations.CreateModel(
            name='ComusLAKGridModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('btm', models.JSONField(blank=True, null=True)),
                ('lnk', models.JSONField(blank=True, null=True)),
                ('sc1', models.JSONField(blank=True, null=True)),
                ('sc2', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_lak_grid',
            },
        ),
        migrations.CreateModel(
            name='ComusLAKPeriodModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_lak_period',
            },
        ),
        migrations.CreateModel(
            name='ComusRCHModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('rechr', models.JSONField(blank=True, null=True)),
                ('rech', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'comus_rch',
            },
        ),
        migrations.CreateModel(
            name='ComusREGModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_reg',
            },
        ),
        migrations.CreateModel(
            name='ComusRESCtrlModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_res_ctrl',
            },
        ),
        migrations.CreateModel(
            name='ComusRESGridModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('btm', models.JSONField(blank=True, null=True)),
                ('bvk', models.JSONField(blank=True, null=True)),
                ('btk', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_res_grid',
            },
        ),
        migrations.CreateModel(
            name='ComusRESPeriodModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_res_period',
            },
        ),
        migrations.CreateModel(
            name='ComusRIVModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('cond', models.JSONField(blank=True, null=True)),
                ('shead', models.JSONField(blank=True, null=True)),
                ('ehead', models.JSONField(blank=True, null=True)),
                ('riv_btm', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_riv',
            },
        ),
        migrations.CreateModel(
            name='ComusSHBModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('shead', models.JSONField(blank=True, null=True)),
                ('ehead', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_shb',
            },
        ),
        migrations.CreateModel(
            name='ComusSTRCtrlModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_str_ctrl',
            },
        ),
        migrations.CreateModel(
            name='ComusSTRDrnModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('delev', models.JSONField(blank=True, null=True)),
                ('cond', models.JSONField(blank=True, null=True)),
                ('segm_id', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_str_drn',
            },
        ),
        migrations.CreateModel(
            name='ComusSTRGridModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('cell_id', models.JSONField(blank=True, null=True)),
                ('length', models.JSONField(blank=True, null=True)),
                ('btm', models.JSONField(blank=True, null=True)),
                ('bwdt', models.JSONField(blank=True, null=True)),
                ('sizh1', models.JSONField(blank=True, null=True)),
                ('sizh2', models.JSONField(blank=True, null=True)),
                ('bvk', models.JSONField(blank=True, null=True)),
                ('btk', models.JSONField(blank=True, null=True)),
                ('slp', models.JSONField(blank=True, null=True)),
                ('ndc', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_str_grid',
            },
        ),
        migrations.CreateModel(
            name='ComusSTRPeriodModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_str_period',
            },
        ),
        migrations.CreateModel(
            name='ComusSTRWaterUseModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('wureg_id', models.JSONField(blank=True, null=True)),
                ('ratio', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_str_water_use',
            },
        ),
        migrations.CreateModel(
            name='ComusSUBCtrlModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('num_ndb', models.IntegerField()),
                ('num_db', models.IntegerField()),
                ('num_mz', models.IntegerField()),
                ('nn', models.IntegerField()),
                ('acc', models.FloatField()),
                ('it_min', models.IntegerField()),
                ('dsh_opt', models.IntegerField()),
            ],
            options={
                'db_table': 'comus_sub_ctrl',
            },
        ),
        migrations.CreateModel(
            name='ComusSUBDbGridModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('rnb', models.JSONField(blank=True, null=True)),
                ('dsh', models.JSONField(blank=True, null=True)),
                ('dhc', models.JSONField(blank=True, null=True)),
                ('dcom', models.JSONField(blank=True, null=True)),
                ('dz', models.JSONField(blank=True, null=True)),
                ('imz', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_sub_db_grid',
            },
        ),
        migrations.CreateModel(
            name='ComusSUBDbLyrModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_sub_db_lyr',
            },
        ),
        migrations.CreateModel(
            name='ComusSUBMzModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_sub_mz',
            },
        ),
        migrations.CreateModel(
            name='ComusSUBNdbGridModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('hc', models.JSONField(blank=True, null=True)),
                ('sfe', models.JSONField(blank=True, null=True)),
                ('sfv', models.JSONField(blank=True, null=True)),
                ('com', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_sub_ndb_grid',
            },
        ),
        migrations.CreateModel(
            name='ComusSUBNdbLyrModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_sub_ndb_lyr',
            },
        ),
        migrations.CreateModel(
            name='ComusWELModel',
            fields=[
                ('comus_dis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ComusDis.comusdismodel')),
                ('wellr', models.JSONField(blank=True, null=True)),
                ('satthr', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comus_wel',
            },
        ),
    ]
